#include "codegen/codegen.hpp"

#include <cctype>
#include <stdexcept>

namespace ebasic {

std::string Codegen::mangleName(const std::string& name) {
    std::string r = "eb_";
    for (char c : name) r.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(c))));
    return r;
}

std::string Codegen::cppType(TypeKind type) {
    switch (type) {
        case TypeKind::Integer: return "int32_t";
        case TypeKind::Double: return "double";
        case TypeKind::StringT: return "::ebasic::rt::BString";
        case TypeKind::Unknown: break;
    }
    throw std::runtime_error("codegen: unresolved type reached codegen");
}

std::string Codegen::escapeStringLiteral(const std::string& s) {
    std::string out;
    out.push_back('"');
    for (char c : s) {
        switch (c) {
            case '"': out += "\\\""; break;
            case '\\': out += "\\\\"; break;
            case '\n': out += "\\n"; break;
            default: out.push_back(c);
        }
    }
    out.push_back('"');
    return out;
}

std::string Codegen::genExpr(const Expr& expr) {
    switch (expr.kind) {
        case ExprKind::IntLiteral:
            return std::to_string(expr.intValue);
        case ExprKind::DoubleLiteral:
            return std::to_string(expr.doubleValue);
        case ExprKind::StringLiteral:
            return "::ebasic::rt::BString(" + escapeStringLiteral(expr.stringValue) + ")";
        case ExprKind::Ident:
            return mangleName(expr.stringValue);
        case ExprKind::UnaryNeg:
            return "(-" + genExpr(*expr.lhs) + ")";
        case ExprKind::Binary: {
            const char* op = "+";
            switch (expr.binOp) {
                case BinOp::Add: op = "+"; break;
                case BinOp::Sub: op = "-"; break;
                case BinOp::Mul: op = "*"; break;
                case BinOp::Div: op = "/"; break;
                case BinOp::Concat: op = "+"; break;
            }
            return "(" + genExpr(*expr.lhs) + " " + op + " " + genExpr(*expr.rhs) + ")";
        }
    }
    throw std::runtime_error("codegen: unknown expression kind");
}

void Codegen::genStmt(const Stmt& stmt, std::ostringstream& out) {
    switch (stmt.kind) {
        case StmtKind::Dim:
            out << "    " << cppType(stmt.declaredType) << " " << mangleName(stmt.name) << "{};\n";
            return;
        case StmtKind::Assign:
            out << "    " << mangleName(stmt.name) << " = " << genExpr(*stmt.expr) << ";\n";
            return;
        case StmtKind::Print: {
            out << "    ::ebasic::rt::printLine(";
            for (size_t i = 0; i < stmt.args.size(); ++i) {
                if (i > 0) out << ", ";
                out << genExpr(*stmt.args[i]);
            }
            out << ");\n";
            return;
        }
    }
}

std::string Codegen::generate(const Module& module) {
    std::ostringstream out;
    out << "// Generated by ebc. Do not edit.\n";
    out << "#include \"ebasic/runtime/runtime.hpp\"\n\n";
    out << "int main() {\n";
    for (const auto& stmt : module.stmts) {
        genStmt(*stmt, out);
    }
    out << "    return 0;\n";
    out << "}\n";
    return out.str();
}

} // namespace ebasic
