#include "lockfile.hpp"

#include <filesystem>
#include <fstream>
#include <sstream>

namespace fs = std::filesystem;

namespace ebpm {

bool writeLockfile(const std::string& rootDir, const std::vector<ResolvedPackage>& order,
                    std::string& err) {
    fs::path lockPath = fs::path(rootDir) / "ebasic.lock";
    std::ostringstream out;
    out << "# Auto-generated by ebpm - do not edit by hand.\n";
    // `order`'s last entry is always the root package itself (see
    // resolveDependencyGraph's doc comment) - the lockfile only needs to
    // describe the root's dependencies, not the root itself.
    for (size_t i = 0; i + 1 < order.size(); ++i) {
        const ResolvedPackage& pkg = order[i];
        out << "\n[[package]]\n";
        out << "name = \"" << pkg.name << "\"\n";
        out << "path = \"" << pkg.dir << "\"\n";
    }

    std::ofstream file(lockPath);
    if (!file) {
        err = "could not write '" + lockPath.string() + "'";
        return false;
    }
    file << out.str();
    return true;
}

} // namespace ebpm
