#include "lockfile.hpp"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <toml++/toml.hpp>

namespace fs = std::filesystem;

namespace ebpm {

bool writeLockfile(const std::string& rootDir, const std::vector<ResolvedPackage>& order,
                    std::string& err) {
    fs::path lockPath = fs::path(rootDir) / "ebasic.lock";
    std::ostringstream out;
    out << "# Auto-generated by ebpm - do not edit by hand.\n";
    // `order`'s last entry is always the root package itself (see
    // resolveDependencyGraph's doc comment) - the lockfile only needs to
    // describe the root's dependencies, not the root itself.
    for (size_t i = 0; i + 1 < order.size(); ++i) {
        const ResolvedPackage& pkg = order[i];
        out << "\n[[package]]\n";
        out << "name = \"" << pkg.name << "\"\n";
        out << "path = \"" << pkg.dir << "\"\n";
        if (!pkg.gitCommit.empty()) {
            out << "commit = \"" << pkg.gitCommit << "\"\n";
        }
    }

    std::ofstream file(lockPath);
    if (!file) {
        err = "could not write '" + lockPath.string() + "'";
        return false;
    }
    file << out.str();
    return true;
}

std::unordered_map<std::string, std::string> readLockfilePins(const std::string& rootDir) {
    std::unordered_map<std::string, std::string> pins;
    fs::path lockPath = fs::path(rootDir) / "ebasic.lock";
    if (!fs::exists(lockPath)) return pins;

    toml::table tbl;
    try {
        tbl = toml::parse_file(lockPath.string());
    } catch (const toml::parse_error&) {
        return pins; // a malformed lockfile just means "nothing pinned yet"
    }

    auto packages = tbl["package"];
    if (auto arr = packages.as_array()) {
        for (auto&& entry : *arr) {
            auto entryTbl = entry.as_table();
            if (!entryTbl) continue;
            auto name = (*entryTbl)["name"].value<std::string>();
            auto commit = (*entryTbl)["commit"].value<std::string>();
            if (name && commit && !commit->empty()) pins[*name] = *commit;
        }
    }
    return pins;
}

} // namespace ebpm
