#include "lockfile.hpp"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <toml++/toml.hpp>

namespace fs = std::filesystem;

namespace ebpm {

namespace {

/// Escapes a value for a TOML basic string (`"` and `\` are the only
/// characters that need it for the plain ASCII text ever written here).
/// A real, previously-latent bug, not just defensive hygiene: `pkg.dir`
/// is a canonicalized *native* filesystem path - on Windows, that means
/// backslash-separated, unlike a URL or a Unix-style path - and writing
/// it here unescaped means `\a`/`\_`/`\m`/... (not valid TOML escape
/// sequences) silently corrupt the *entire* file. Every later
/// `readLockfilePins` call then catches the resulting parse error and
/// treats it as "nothing pinned yet" - breaking pin-reuse completely and
/// invisibly on Windows, for every dependency kind (not just a registry
/// one), confirmed live via real Windows CI: a temporary diagnostic build
/// showed `readLockfilePins` returning zero pins despite the lockfile
/// visibly containing pin data under a plain text search.
std::string escapeTomlString(const std::string& s) {
    std::string r;
    r.reserve(s.size());
    for (char c : s) {
        if (c == '"' || c == '\\') r.push_back('\\');
        r.push_back(c);
    }
    return r;
}

} // namespace

bool writeLockfile(const std::string& rootDir, const std::vector<ResolvedPackage>& order,
                    std::string& err) {
    fs::path lockPath = fs::path(rootDir) / "ebasic.lock";
    std::ostringstream out;
    out << "# Auto-generated by ebpm - do not edit by hand.\n";
    /// `order`'s last entry is always the root package itself (see
    /// resolveDependencyGraph's doc comment) - the lockfile only needs to
    /// describe the root's dependencies, not the root itself.
    for (size_t i = 0; i + 1 < order.size(); ++i) {
        const ResolvedPackage& pkg = order[i];
        out << "\n[[package]]\n";
        out << "name = \"" << escapeTomlString(pkg.name) << "\"\n";
        out << "path = \"" << escapeTomlString(pkg.dir) << "\"\n";
        if (!pkg.gitCommit.empty()) {
            out << "commit = \"" << escapeTomlString(pkg.gitCommit) << "\"\n";
        }
        if (pkg.sourceKind == SourceKind::Registry) {
            out << "version = \"" << escapeTomlString(pkg.version) << "\"\n";
            out << "git = \"" << escapeTomlString(pkg.registryGit) << "\"\n";
            if (!pkg.registryRef.empty()) {
                out << "ref = \"" << escapeTomlString(pkg.registryRef) << "\"\n";
            }
        }
    }

    std::ofstream file(lockPath);
    if (!file) {
        err = "could not write '" + lockPath.string() + "'";
        return false;
    }
    file << out.str();
    return true;
}

std::unordered_map<std::string, Pin> readLockfilePins(const std::string& rootDir) {
    std::unordered_map<std::string, Pin> pins;
    fs::path lockPath = fs::path(rootDir) / "ebasic.lock";
    if (!fs::exists(lockPath)) return pins;

    toml::table tbl;
    try {
        tbl = toml::parse_file(lockPath.string());
    } catch (const toml::parse_error&) {
        return pins; // a malformed lockfile just means "nothing pinned yet"
    }

    auto packages = tbl["package"];
    if (auto arr = packages.as_array()) {
        for (auto&& entry : *arr) {
            auto entryTbl = entry.as_table();
            if (!entryTbl) continue;
            auto name = (*entryTbl)["name"].value<std::string>();
            if (!name) continue;
            Pin pin;
            pin.commit = (*entryTbl)["commit"].value<std::string>().value_or("");
            pin.version = (*entryTbl)["version"].value<std::string>().value_or("");
            pin.git = (*entryTbl)["git"].value<std::string>().value_or("");
            pin.ref = (*entryTbl)["ref"].value<std::string>().value_or("");
            if (!pin.commit.empty() || !pin.git.empty()) pins[*name] = std::move(pin);
        }
    }
    return pins;
}

} // namespace ebpm
